import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Sidebar
    "sidebar.myReservations": "My Reservations",
    "sidebar.makeReservation": "Make Reservation",
    "sidebar.profile": "Profile",
    "sidebar.adminPanel": "Admin Panel",
    "sidebar.dashboard": "🏠 Dashboard",
    "sidebar.equipment": "🔧 Equipment",
    "sidebar.allReservations": "📋 All Reservations",
    "sidebar.users": "👥 Users",
    "sidebar.goToProfile": "Go to Profile",
    "sidebar.logout": "Logout",

    // Login
    "login.title": "Login",
    "login.subtitle": "Smart Laboratory Equipment Reservation System",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Login",
    "login.loading": "Logging in...",
    "login.noAccount": "Do not have an account?",
    "login.signUp": "Sign Up",

    // Signup
    "signup.title": "Sign Up",
    "signup.subtitle": "Create a new account",
    "signup.username": "Username",
    "signup.fullName": "Full Name",
    "signup.email": "Email",
    "signup.password": "Password",
    "signup.submit": "Create Account",
    "signup.loading": "Creating account...",
    "signup.haveAccount": "Already have an account?",
    "signup.login": "Login",

    // My Reservations
    "myRes.title": "My Reservations",
    "myRes.subtitle": "View your active and past equipment reservations.",
    "myRes.showPast": "Show Past Reservations",
    "myRes.loading": "Loading...",
    "myRes.equipment": "Equipment",
    "myRes.location": "Location",
    "myRes.startTime": "Start Time",
    "myRes.endTime": "End Time",
    "myRes.status": "Status",
    "myRes.noFound": "No reservations found.",
    "myRes.past": "Past",
    "myRes.active": "Active",
    "myRes.failedLoad": "Failed to load reservations.",

    // Make Reservation
    "makeRes.title": "Make a Reservation",
    "makeRes.subtitle": "Select equipment, choose an available day, and reserve a free time slot.",
    "makeRes.equipment": "Equipment",
    "makeRes.selectEquipment": "Select equipment",
    "makeRes.available": "available",
    "makeRes.location": "Location",
    "makeRes.totalQty": "Total Quantity:",
    "makeRes.faultyUnits": "Faulty Units:",
    "makeRes.availableForRes": "Available for Reservation:",
    "makeRes.allBroken": "0 - All equipment is broken or being maintained",
    "makeRes.selectDate": "Select Date",
    "makeRes.previous": "Previous",
    "makeRes.next": "Next",
    "makeRes.legendAvailable": "🟢 Available",
    "makeRes.legendPartial": "🟡 Partially reserved",
    "makeRes.legendFull": "🔴 Full",
    "makeRes.legendPast": "⚪ Past",
    "makeRes.selectTimeSlot": "Select Time Slot",
    "makeRes.noStock": "No stock",
    "makeRes.past": "Past",
    "makeRes.submit": "Reserve",
    "makeRes.loading": "Creating reservation...",
    "makeRes.errSelect": "Please select equipment, date and time slot.",
    "makeRes.errUnavailable": "This equipment is currently unavailable.",
    "makeRes.errPastDate": "Cannot make a reservation for a past date.",
    "makeRes.errFailed": "Failed to create reservation.",
    "makeRes.errLoadEquip": "Failed to load equipment.",

    // Profile
    "profile.title": "My Profile",
    "profile.subtitle": "View your account details and update your password.",
    "profile.name": "Name:",
    "profile.username": "Username:",
    "profile.email": "Email:",
    "profile.changePassword": "Change Password",
    "profile.cancel": "Cancel",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.savePassword": "Save Password",
    "profile.errMismatch": "New password and confirmation do not match.",

    // Admin Dashboard
    "adminDash.title": "Admin Dashboard",
    "adminDash.subtitle": "System overview at a glance.",
    "adminDash.loading": "Loading stats...",
    "adminDash.equipment": "Equipment",
    "adminDash.reservations": "Reservations",
    "adminDash.users": "Users",
    "adminDash.total": "Total",
    "adminDash.active": "Active",
    "adminDash.completed": "Completed",
    "adminDash.cancelled": "Cancelled",
    "adminDash.allEquipment": "All Equipment",
    "adminDash.allReservations": "All Reservations",
    "adminDash.activeReservations": "Active Reservations",
    "adminDash.completedReservations": "Completed Reservations",
    "adminDash.cancelledReservations": "Cancelled Reservations",
    "adminDash.allUsers": "All Users",
    "adminDash.acrossLabs": "across {count} lab(s)",
    "adminDash.modalCols.name": "Name",
    "adminDash.modalCols.status": "Status",
    "adminDash.modalCols.lab": "Lab",
    "adminDash.modalCols.code": "Code",
    "adminDash.modalCols.user": "User",
    "adminDash.modalCols.equipment": "Equipment",
    "adminDash.modalCols.startDate": "Start Date",
    "adminDash.modalCols.endDate": "End Date",
    "adminDash.modalCols.email": "Email",
    "adminDash.modalCols.role": "Role",
    "adminDash.failedLoad": "Failed to load items",

    // Admin Equipment
    "adminEq.title": "Equipment Management",
    "adminEq.subtitle": "Add, edit, and manage laboratory equipment.",
    "adminEq.addBtn": "+ Add Equipment",
    "adminEq.searchPlaceholder": "Search by name, code, lab...",
    "adminEq.allStatuses": "All Statuses",
    "adminEq.loading": "Loading...",
    "adminEq.noFound": "No equipment found.",
    "adminEq.colName": "Name",
    "adminEq.colCode": "Code",
    "adminEq.colLab": "Lab",
    "adminEq.colQtyFaulty": "Qty / Faulty",
    "adminEq.colStatus": "Status",
    "adminEq.colActions": "Actions",
    "adminEq.available": "Available:",
    "adminEq.room": "Room",
    "adminEq.edit": "Edit",
    "adminEq.delete": "Delete",
    "adminEq.editTitle": "Edit Equipment",
    "adminEq.addTitle": "Add Equipment",
    "adminEq.fieldName": "Name",
    "adminEq.fieldCode": "Code",
    "adminEq.fieldDesc": "Description",
    "adminEq.fieldQty": "Quantity",
    "adminEq.fieldFaulty": "Faulty Count",
    "adminEq.fieldLab": "Laboratory",
    "adminEq.selectLab": "Select lab",
    "adminEq.fieldStatus": "Status",
    "adminEq.cancel": "Cancel",
    "adminEq.save": "Save",
    "adminEq.saving": "Saving...",
    "adminEq.errRequired": "Name, code and lab are required.",
    "adminEq.confirmDelete": 'Delete "{name}"? Active reservations for this equipment will be cancelled.',

    // Admin Reservations
    "adminRes.title": "All Reservations",
    "adminRes.subtitle": "View and cancel any reservation across all users.",
    "adminRes.searchPlaceholder": "Search by user, equipment...",
    "adminRes.allStatuses": "All Statuses",
    "adminRes.active": "Active",
    "adminRes.cancelled": "Cancelled",
    "adminRes.completed": "Completed",
    "adminRes.loading": "Loading...",
    "adminRes.noFound": "No reservations found.",
    "adminRes.colUser": "User",
    "adminRes.colEquipment": "Equipment",
    "adminRes.colLocation": "Location",
    "adminRes.colStart": "Start",
    "adminRes.colEnd": "End",
    "adminRes.colStatus": "Status",
    "adminRes.colActions": "Actions",
    "adminRes.cancelBtn": "Cancel",
    "adminRes.confirmCancel": "Cancel this reservation?",
    "adminRes.showing": "Showing {filtered} of {total} reservations",

    // Admin Users
    "adminUsers.title": "User Management",
    "adminUsers.subtitle": "View all users and manage their roles.",
    "adminUsers.searchPlaceholder": "Search by name, username, email...",
    "adminUsers.allRoles": "All Roles",
    "adminUsers.loading": "Loading...",
    "adminUsers.noFound": "No users found.",
    "adminUsers.colName": "Name",
    "adminUsers.colUsername": "Username",
    "adminUsers.colEmail": "Email",
    "adminUsers.colCurrentRole": "Current Role",
    "adminUsers.colChangeRole": "Change Role",
    "adminUsers.colJoined": "Joined",
    "adminUsers.you": "← you",
    "adminUsers.saving": "Saving...",
    "adminUsers.cannotDemote": "You cannot demote yourself",
    "adminUsers.showing": "Showing {filtered} of {total} users",

    // Admin List Modal
    "modal.loading": "Loading...",
    "modal.noItems": "No items found.",
    "modal.close": "Close",

    // Language toggle
    "lang.toggle": "TR",
  },

  tr: {
    // Sidebar
    "sidebar.myReservations": "Rezervasyonlarım",
    "sidebar.makeReservation": "Rezervasyon Yap",
    "sidebar.profile": "Profil",
    "sidebar.adminPanel": "Yönetici Paneli",
    "sidebar.dashboard": "🏠 Panel",
    "sidebar.equipment": "🔧 Ekipman",
    "sidebar.allReservations": "📋 Tüm Rezervasyonlar",
    "sidebar.users": "👥 Kullanıcılar",
    "sidebar.goToProfile": "Profile Git",
    "sidebar.logout": "Çıkış Yap",

    // Login
    "login.title": "Giriş Yap",
    "login.subtitle": "Akıllı Laboratuvar Ekipmanı Rezervasyon Sistemi",
    "login.email": "E-posta",
    "login.password": "Şifre",
    "login.submit": "Giriş Yap",
    "login.loading": "Giriş yapılıyor...",
    "login.noAccount": "Hesabınız yok mu?",
    "login.signUp": "Kayıt Ol",

    // Signup
    "signup.title": "Kayıt Ol",
    "signup.subtitle": "Yeni hesap oluştur",
    "signup.username": "Kullanıcı Adı",
    "signup.fullName": "Ad Soyad",
    "signup.email": "E-posta",
    "signup.password": "Şifre",
    "signup.submit": "Hesap Oluştur",
    "signup.loading": "Hesap oluşturuluyor...",
    "signup.haveAccount": "Zaten hesabınız var mı?",
    "signup.login": "Giriş Yap",

    // My Reservations
    "myRes.title": "Rezervasyonlarım",
    "myRes.subtitle": "Aktif ve geçmiş ekipman rezervasyonlarınızı görüntüleyin.",
    "myRes.showPast": "Geçmiş Rezervasyonları Göster",
    "myRes.loading": "Yükleniyor...",
    "myRes.equipment": "Ekipman",
    "myRes.location": "Konum",
    "myRes.startTime": "Başlangıç",
    "myRes.endTime": "Bitiş",
    "myRes.status": "Durum",
    "myRes.noFound": "Rezervasyon bulunamadı.",
    "myRes.past": "Geçmiş",
    "myRes.active": "Aktif",
    "myRes.failedLoad": "Rezervasyonlar yüklenemedi.",

    // Make Reservation
    "makeRes.title": "Rezervasyon Yap",
    "makeRes.subtitle": "Ekipman seçin, uygun bir gün seçin ve boş bir zaman dilimi rezerve edin.",
    "makeRes.equipment": "Ekipman",
    "makeRes.selectEquipment": "Ekipman seçin",
    "makeRes.available": "mevcut",
    "makeRes.location": "Konum",
    "makeRes.totalQty": "Toplam Adet:",
    "makeRes.faultyUnits": "Arızalı Adet:",
    "makeRes.availableForRes": "Rezervasyon İçin Mevcut:",
    "makeRes.allBroken": "0 - Tüm ekipmanlar arızalı veya bakımda",
    "makeRes.selectDate": "Tarih Seçin",
    "makeRes.previous": "Önceki",
    "makeRes.next": "Sonraki",
    "makeRes.legendAvailable": "🟢 Uygun",
    "makeRes.legendPartial": "🟡 Kısmen dolu",
    "makeRes.legendFull": "🔴 Dolu",
    "makeRes.legendPast": "⚪ Geçmiş",
    "makeRes.selectTimeSlot": "Zaman Dilimi Seçin",
    "makeRes.noStock": "Stok yok",
    "makeRes.past": "Geçmiş",
    "makeRes.submit": "Rezerve Et",
    "makeRes.loading": "Rezervasyon oluşturuluyor...",
    "makeRes.errSelect": "Lütfen ekipman, tarih ve saat seçiniz.",
    "makeRes.errUnavailable": "Bu ekipman şu anda mevcut değildir.",
    "makeRes.errPastDate": "Geçmiş bir tarihte rezervasyon yapılamaz.",
    "makeRes.errFailed": "Rezervasyon oluşturulamadı.",
    "makeRes.errLoadEquip": "Ekipmanlar yüklenemedi.",

    // Profile
    "profile.title": "Profilim",
    "profile.subtitle": "Hesap bilgilerinizi görüntüleyin ve şifrenizi güncelleyin.",
    "profile.name": "Ad Soyad:",
    "profile.username": "Kullanıcı Adı:",
    "profile.email": "E-posta:",
    "profile.changePassword": "Şifre Değiştir",
    "profile.cancel": "İptal",
    "profile.currentPassword": "Mevcut Şifre",
    "profile.newPassword": "Yeni Şifre",
    "profile.confirmPassword": "Yeni Şifre (Tekrar)",
    "profile.savePassword": "Şifreyi Kaydet",
    "profile.errMismatch": "Yeni şifre ve onay şifresi eşleşmiyor.",

    // Admin Dashboard
    "adminDash.title": "Yönetici Paneli",
    "adminDash.subtitle": "Sisteme genel bakış.",
    "adminDash.loading": "İstatistikler yükleniyor...",
    "adminDash.equipment": "Ekipman",
    "adminDash.reservations": "Rezervasyonlar",
    "adminDash.users": "Kullanıcılar",
    "adminDash.total": "Toplam",
    "adminDash.active": "Aktif",
    "adminDash.completed": "Tamamlandı",
    "adminDash.cancelled": "İptal Edildi",
    "adminDash.allEquipment": "Tüm Ekipmanlar",
    "adminDash.allReservations": "Tüm Rezervasyonlar",
    "adminDash.activeReservations": "Aktif Rezervasyonlar",
    "adminDash.completedReservations": "Tamamlanan Rezervasyonlar",
    "adminDash.cancelledReservations": "İptal Edilen Rezervasyonlar",
    "adminDash.allUsers": "Tüm Kullanıcılar",
    "adminDash.acrossLabs": "{count} laboratuvar üzerinden",
    "adminDash.modalCols.name": "Ad",
    "adminDash.modalCols.status": "Durum",
    "adminDash.modalCols.lab": "Lab",
    "adminDash.modalCols.code": "Kod",
    "adminDash.modalCols.user": "Kullanıcı",
    "adminDash.modalCols.equipment": "Ekipman",
    "adminDash.modalCols.startDate": "Başlangıç",
    "adminDash.modalCols.endDate": "Bitiş",
    "adminDash.modalCols.email": "E-posta",
    "adminDash.modalCols.role": "Rol",
    "adminDash.failedLoad": "Öğeler yüklenemedi",

    // Admin Equipment
    "adminEq.title": "Ekipman Yönetimi",
    "adminEq.subtitle": "Laboratuvar ekipmanlarını ekleyin, düzenleyin ve yönetin.",
    "adminEq.addBtn": "+ Ekipman Ekle",
    "adminEq.searchPlaceholder": "Ad, kod, lab ile ara...",
    "adminEq.allStatuses": "Tüm Durumlar",
    "adminEq.loading": "Yükleniyor...",
    "adminEq.noFound": "Ekipman bulunamadı.",
    "adminEq.colName": "Ad",
    "adminEq.colCode": "Kod",
    "adminEq.colLab": "Lab",
    "adminEq.colQtyFaulty": "Adet / Arızalı",
    "adminEq.colStatus": "Durum",
    "adminEq.colActions": "İşlemler",
    "adminEq.available": "Mevcut:",
    "adminEq.room": "Oda",
    "adminEq.edit": "Düzenle",
    "adminEq.delete": "Sil",
    "adminEq.editTitle": "Ekipmanı Düzenle",
    "adminEq.addTitle": "Ekipman Ekle",
    "adminEq.fieldName": "Ad",
    "adminEq.fieldCode": "Kod",
    "adminEq.fieldDesc": "Açıklama",
    "adminEq.fieldQty": "Adet",
    "adminEq.fieldFaulty": "Arızalı Adet",
    "adminEq.fieldLab": "Laboratuvar",
    "adminEq.selectLab": "Lab seçin",
    "adminEq.fieldStatus": "Durum",
    "adminEq.cancel": "İptal",
    "adminEq.save": "Kaydet",
    "adminEq.saving": "Kaydediliyor...",
    "adminEq.errRequired": "Ad, kod ve laboratuvar zorunludur.",
    "adminEq.confirmDelete": '"{name}" silinsin mi? Bu ekipman için aktif rezervasyonlar iptal edilecektir.',

    // Admin Reservations
    "adminRes.title": "Tüm Rezervasyonlar",
    "adminRes.subtitle": "Tüm kullanıcılara ait rezervasyonları görüntüleyin ve iptal edin.",
    "adminRes.searchPlaceholder": "Kullanıcı, ekipman ile ara...",
    "adminRes.allStatuses": "Tüm Durumlar",
    "adminRes.active": "Aktif",
    "adminRes.cancelled": "İptal Edildi",
    "adminRes.completed": "Tamamlandı",
    "adminRes.loading": "Yükleniyor...",
    "adminRes.noFound": "Rezervasyon bulunamadı.",
    "adminRes.colUser": "Kullanıcı",
    "adminRes.colEquipment": "Ekipman",
    "adminRes.colLocation": "Konum",
    "adminRes.colStart": "Başlangıç",
    "adminRes.colEnd": "Bitiş",
    "adminRes.colStatus": "Durum",
    "adminRes.colActions": "İşlemler",
    "adminRes.cancelBtn": "İptal Et",
    "adminRes.confirmCancel": "Bu rezervasyon iptal edilsin mi?",
    "adminRes.showing": "{filtered} / {total} rezervasyon gösteriliyor",

    // Admin Users
    "adminUsers.title": "Kullanıcı Yönetimi",
    "adminUsers.subtitle": "Tüm kullanıcıları görüntüleyin ve rollerini yönetin.",
    "adminUsers.searchPlaceholder": "Ad, kullanıcı adı, e-posta ile ara...",
    "adminUsers.allRoles": "Tüm Roller",
    "adminUsers.loading": "Yükleniyor...",
    "adminUsers.noFound": "Kullanıcı bulunamadı.",
    "adminUsers.colName": "Ad",
    "adminUsers.colUsername": "Kullanıcı Adı",
    "adminUsers.colEmail": "E-posta",
    "adminUsers.colCurrentRole": "Mevcut Rol",
    "adminUsers.colChangeRole": "Rol Değiştir",
    "adminUsers.colJoined": "Katılım",
    "adminUsers.you": "← siz",
    "adminUsers.saving": "Kaydediliyor...",
    "adminUsers.cannotDemote": "Kendinizi düşüremezsiniz",
    "adminUsers.showing": "{filtered} / {total} kullanıcı gösteriliyor",

    // Admin List Modal
    "modal.loading": "Yükleniyor...",
    "modal.noItems": "Öğe bulunamadı.",
    "modal.close": "Kapat",

    // Language toggle
    "lang.toggle": "EN",
  },
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");

  const toggleLanguage = () =>
    setLanguage((prev) => (prev === "en" ? "tr" : "en"));

  const t = (key, vars = {}) => {
    let text = translations[language][key] || key;
    Object.entries(vars).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
